<a href="https://colab.research.google.com/github/z018/CJL/blob/main/AIDL_20220304.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**清單查看現有的Package版本**



In [ ]:
pip list

Package                       Version
----------------------------- ---------------------
absl-py                       1.0.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.2.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.11.4
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.4.0
audioread                     2.1.9
autograd                      1.3
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        4.1.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.4
branca                        0.4.2
bs4                           0.0.1
CacheC

**套件版本確認**

In [ ]:
# -*- 版本檢查 -*-
import pandas as pd
print("pandas version: %s" %pd.__version__)
import numpy as np
print("numpy version: %s" %np.__version__)
import matplotlib
print("matplotlib version: %s" %matplotlib.__version__)
import sklearn
print("sklearn version: %s" %sklearn.__version__)


pandas version: 1.3.5
numpy version: 1.21.5
matplotlib version: 3.2.2
sklearn version: 1.0.2


作業路徑


https://github.com/MyDearGreatTeacher/2022_1_courses/blob/main/%E4%BA%BA%E5%B7%A5%E6%99%BA%E6%85%A7%E5%B0%8E%E8%AB%96/numpy_%E7%B7%B4%E7%BF%92_20220302.md

In [18]:
# -*- numpy 實作 -*-
import numpy as np
b = np.linspace(0, 2, 4) # -*- numpy 0-2分成四份 -*-
print(b)

c = np.linspace(0, 2, 4, endpoint=False) # -*- numpy 0-2分成四份，但不包含2 -*-
print(c)

# -*- 產生一個 2D array -*-
print('')
ar2=np.array([[0,3,5],[2,8,7]])
print(ar2)
print('')
print(ar2.ndim) # -*- 維度_軸的數量或維度的數量 -*-
print(ar2.shape) # -*- 形狀_行m列。 本題為例:2行3列 -*-
print(ar2.size) # -*- 大小 -*-


[0.         0.66666667 1.33333333 2.        ]
[0.  0.5 1.  1.5]

[[0 3 5]
 [2 8 7]]

2
(2, 3)
6


In [5]:

# -*- ndarray的屬性:dtyp(資料型態) -*-
import numpy as np
ar1=np.array([2,4,6,8]);
print(ar1.dtype) 

ar2=np.array([2,-1,6,3], dtype='float' )
print(ar2.dtype)

ar3=np.array([2.,4,6,8]); 
print(ar3.dtype)


# -*- ndarray的運算:型態轉換|astype()函式 (型態轉換) -*-

f_ar = np.array([13,-3,8.88])
print(f_ar)

intf_ar=f_ar.astype(int)
print(intf_ar)

int64
float64
float64
[13.   -3.    8.88]
[13 -3  8]


In [24]:
import numpy as np
print('對角線顯示1')
ar9=np.eye(3)
print(ar9)        # -*- 對角線地方為1 其餘為0 -*-

print('對角線顯示2,1,4,6') 
ar10=np.diag([2,1,4,6])
print(ar10)       # -*- 對角線顯示給予得數值 -*-

print('二維陣列_橫軸')
b=np.array([range(i,i+3) for i in [2,4,6]]) #-*-橫軸計算 234-*-
                              # 456
                              # 678
print(b)
print('')
print(b.shape)
print(b.ndim)
print(b.dtype)

對角線顯示1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
對角線顯示2,1,4,6
[[2 0 0 0]
 [0 1 0 0]
 [0 0 4 0]
 [0 0 0 6]]
二維陣列_橫軸
[[2 3 4]
 [4 5 6]
 [6 7 8]]

(3, 3)
2
int64


In [25]:
# -*- tile -*-
import numpy as np
a1=np.tile(np.array([[1,2],[6,7]]),3)
print('前面先重複3次，在換後面重複3次')
print(a1)
a2=np.tile(np.array([[1,2],[6,7]]),(2,2))
print('[前面先重複2次，再換後面重複2次]，依這組順序為一個單位，再重複1次')
print(a2)


前面先重複3次，在換後面重複3次
[[1 2 1 2 1 2]
 [6 7 6 7 6 7]]
[前面先重複2次，再換後面重複2次]，依這組順序為一個單位，再重複1次
[[1 2 1 2]
 [6 7 6 7]
 [1 2 1 2]
 [6 7 6 7]]


 **參數數學計算**

In [30]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]]);
x1=ar.sum()
x2=ar.mean()
x3=np.median(ar)

print(x1)
print(x2)
print(x3)

54
6.0
6.0


In [ ]:
ar=range(1000)
%timeit[ar[i]**3for i in ar]

1000 loops, best of 5: 399 µs per loop


In [ ]:
ar=np.arange(1000)
%timeit ar**3


The slowest run took 39.56 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 3.64 µs per loop


In [ ]:
import numpy as np
ar=np.array([[1,1],[1,1]]);
ar2=np.array([[2,2],[2,2]]);
ar*ar2
ar.dot(ar2 )

array([[4, 4],
       [4, 4]])

**seed(0) 抓上次亂數的答案，不讓牠跑掉**

In [ ]:
import numpy as np
np.random.seed(0)